{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "tpJg3xIfOpIw",
        "outputId": "a545757c-bed1-44f6-fb17-90af009c3c64"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting flask-ngrok\n",
            "  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (2.23.0)\n",
            "Requirement already satisfied: Flask>=0.8 in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (1.1.4)\n",
            "Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.0.1)\n",
            "Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (2.11.3)\n",
            "Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (7.1.2)\n",
            "Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.1.0)\n",
            "Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask>=0.8->flask-ngrok) (2.0.1)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2021.10.8)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (3.0.4)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (1.24.3)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2.10)\n",
            "Installing collected packages: flask-ngrok\n",
            "Successfully installed flask-ngrok-0.0.25\n",
            "Collecting sumy\n",
            "  Downloading sumy-0.9.0-py2.py3-none-any.whl (87 kB)\n",
            "\u001b[K     |████████████████████████████████| 87 kB 5.5 MB/s \n",
            "\u001b[?25hRequirement already satisfied: nltk>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from sumy) (3.2.5)\n",
            "Collecting pycountry>=18.2.23\n",
            "  Downloading pycountry-20.7.3.tar.gz (10.1 MB)\n",
            "\u001b[K     |████████████████████████████████| 10.1 MB 36.0 MB/s \n",
            "\u001b[?25hRequirement already satisfied: docopt<0.7,>=0.6.1 in /usr/local/lib/python3.7/dist-packages (from sumy) (0.6.2)\n",
            "Requirement already satisfied: requests>=2.7.0 in /usr/local/lib/python3.7/dist-packages (from sumy) (2.23.0)\n",
            "Collecting breadability>=0.1.20\n",
            "  Downloading breadability-0.1.20.tar.gz (32 kB)\n",
            "Requirement already satisfied: chardet in /usr/local/lib/python3.7/dist-packages (from breadability>=0.1.20->sumy) (3.0.4)\n",
            "Requirement already satisfied: lxml>=2.0 in /usr/local/lib/python3.7/dist-packages (from breadability>=0.1.20->sumy) (4.2.6)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from nltk>=3.0.2->sumy) (1.15.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->sumy) (2021.10.8)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->sumy) (1.24.3)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.7.0->sumy) (2.10)\n",
            "Building wheels for collected packages: breadability, pycountry\n",
            "  Building wheel for breadability (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for breadability: filename=breadability-0.1.20-py2.py3-none-any.whl size=21711 sha256=7eb9d098d4f15c4091b48b789858756d15bd57bbe0ab69133812498a23fbf835\n",
            "  Stored in directory: /root/.cache/pip/wheels/d4/bf/51/81d27ad638e1a6dca4f362ecc33d1e2c764b8ea7ec751b8fc1\n",
            "  Building wheel for pycountry (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "  Created wheel for pycountry: filename=pycountry-20.7.3-py2.py3-none-any.whl size=10746883 sha256=ae974192a9af43a7fac01725f4163086a0f9ba9d2293ab2aeb268cbab0d5dc86\n",
            "  Stored in directory: /root/.cache/pip/wheels/57/e8/3f/120ccc1ff7541c108bc5d656e2a14c39da0d824653b62284c6\n",
            "Successfully built breadability pycountry\n",
            "Installing collected packages: pycountry, breadability, sumy\n",
            "Successfully installed breadability-0.1.20 pycountry-20.7.3 sumy-0.9.0\n",
            "Collecting youtube_transcript_api\n",
            "  Downloading youtube_transcript_api-0.4.3-py3-none-any.whl (23 kB)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from youtube_transcript_api) (2.23.0)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->youtube_transcript_api) (2.10)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->youtube_transcript_api) (3.0.4)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->youtube_transcript_api) (1.24.3)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->youtube_transcript_api) (2021.10.8)\n",
            "Installing collected packages: youtube-transcript-api\n",
            "Successfully installed youtube-transcript-api-0.4.3\n"
          ]
        }
      ],
      "source": [
        "!pip install flask-ngrok\n",
        "!pip install sumy\n",
        "!pip install youtube_transcript_api"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "7Wr67HdPPCGj"
      },
      "outputs": [],
      "source": [
        "from flask_ngrok import run_with_ngrok\n",
        "from flask import Flask, request, jsonify,send_file\n",
        "import time\n",
        "import base64\n",
        "import csv\n",
        "import requests\n",
        "# Summarizer Import (Our Another File: summarizer.py)\n",
        "from Summarizer import sumy_lsa_summarize, sumy_luhn_summarize, sumy_text_rank_summarize, sumy_lex_rank_summarize, sumy_klsum_rank_summarize"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "etE6L8FoYe0c",
        "outputId": "0807b49d-8000-446f-dda4-395c3ad4e0d1"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[nltk_data] Downloading package punkt to /root/nltk_data...\n",
            "[nltk_data]   Unzipping tokenizers/punkt.zip.\n"
          ]
        }
      ],
      "source": [
        "# Sumy Imports\n",
        "from sumy.parsers.plaintext import PlaintextParser\n",
        "from sumy.nlp.tokenizers import Tokenizer\n",
        "from sumy.summarizers.lsa import LsaSummarizer\n",
        "from sumy.summarizers.luhn import LuhnSummarizer\n",
        "from sumy.summarizers.text_rank import TextRankSummarizer\n",
        "from sumy.summarizers.lex_rank import LexRankSummarizer\n",
        "from sumy.summarizers.kl import KLSummarizer\n",
        "from sumy.nlp.stemmers import Stemmer\n",
        "from sumy.utils import get_stop_words\n",
        "\n",
        "# Other Imports\n",
        "from string import punctuation\n",
        "from heapq import nlargest\n",
        "from youtube_transcript_api import YouTubeTranscriptApi, NoTranscriptFound, VideoUnavailable, TooManyRequests, \\\n",
        "    TranscriptsDisabled, NoTranscriptAvailable\n",
        "from youtube_transcript_api.formatters import TextFormatter\n",
        "\n",
        "import nltk\n",
        "nltk.download('punkt')\n",
        "\n",
        "# NLTK Imports\n",
        "from nltk.corpus import stopwords\n",
        "from nltk.tokenize import word_tokenize, sent_tokenize\n",
        "\n",
        "import nltk\n",
        "from nltk.corpus import stopwords\n",
        "from nltk.tokenize import word_tokenize\n",
        "import nltk.classify.util as util\n",
        "from nltk.classify import NaiveBayesClassifier\n",
        "from nltk.metrics import BigramAssocMeasures\n",
        "from nltk.collocations import BigramCollocationFinder as BCF\n",
        "import itertools\n",
        "import pickle\n",
        "nltk.download('punkt')"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "from classifier import commentExtract, sentiment"
      ],
      "metadata": {
        "id": "Xm-G_s2Y5RxF"
      },
      "execution_count": 15,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": 16,
      "metadata": {
        "id": "DTvQI0SNPORY"
      },
      "outputs": [],
      "source": [
        "app = Flask(__name__)\n",
        "run_with_ngrok(app)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RmND-ZU6PSGo",
        "outputId": "e6828fa4-d47b-422b-a739-5d22ae9f0890"
      },
      "outputs": [
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            " * Serving Flask app \"__main__\" (lazy loading)\n",
            " * Environment: production\n",
            "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
            "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
            " * Debug mode: off\n"
          ]
        },
        {
          "metadata": {
            "tags": null
          },
          "name": "stderr",
          "output_type": "stream",
          "text": [
            " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n"
          ]
        },
        {
          "metadata": {
            "tags": null
          },
          "name": "stdout",
          "output_type": "stream",
          "text": [
            " * Running on http://5dae-34-86-132-116.ngrok.io\n",
            " * Traffic stats available on http://127.0.0.1:4040\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "127.0.0.1 - - [14/Dec/2021 17:26:58] \"\u001b[31m\u001b[1mGET /summarize/?id=vnVwvPpdFeY&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 400 -\n",
            "127.0.0.1 - - [14/Dec/2021 17:28:29] \"\u001b[37mGET /summarize/?id=vnVwvPpdFeY&percent=50&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 200 -\n",
            "127.0.0.1 - - [14/Dec/2021 17:28:38] \"\u001b[31m\u001b[1mGET /summarize/?id=vnVwvPpdFeY&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 400 -\n",
            "[2021-12-14 17:31:54,448] ERROR in app: Exception on /summarize/ [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 2447, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1821, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 39, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"<ipython-input-17-7614ea4eb6dc>\", line 21, in transcript_fetched_query\n",
            "    transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 128, in get_transcript\n",
            "    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 70, in list_transcripts\n",
            "    return TranscriptListFetcher(http_client).fetch(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 47, in fetch\n",
            "    self._extract_captions_json(self._fetch_video_html(video_id), video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 59, in _extract_captions_json\n",
            "    raise TranscriptsDisabled(video_id)\n",
            "youtube_transcript_api._errors.TranscriptsDisabled: \n",
            "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=3TchUWKmW_M! This is most likely caused by:\n",
            "\n",
            "Subtitles are disabled for this video\n",
            "\n",
            "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
            "127.0.0.1 - - [14/Dec/2021 17:31:54] \"\u001b[35m\u001b[1mGET /summarize/?id=3TchUWKmW_M&percent=20&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 500 -\n",
            "[2021-12-14 17:32:30,079] ERROR in app: Exception on /summarize/ [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 2447, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1821, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 39, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"<ipython-input-17-7614ea4eb6dc>\", line 21, in transcript_fetched_query\n",
            "    transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 128, in get_transcript\n",
            "    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 70, in list_transcripts\n",
            "    return TranscriptListFetcher(http_client).fetch(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 47, in fetch\n",
            "    self._extract_captions_json(self._fetch_video_html(video_id), video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 59, in _extract_captions_json\n",
            "    raise TranscriptsDisabled(video_id)\n",
            "youtube_transcript_api._errors.TranscriptsDisabled: \n",
            "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=undefined! This is most likely caused by:\n",
            "\n",
            "Subtitles are disabled for this video\n",
            "\n",
            "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
            "127.0.0.1 - - [14/Dec/2021 17:32:30] \"\u001b[35m\u001b[1mGET /summarize/?id=undefined&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 500 -\n",
            "[2021-12-14 17:32:56,731] ERROR in app: Exception on /summarize/ [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 2447, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1821, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 39, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"<ipython-input-17-7614ea4eb6dc>\", line 21, in transcript_fetched_query\n",
            "    transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 128, in get_transcript\n",
            "    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 70, in list_transcripts\n",
            "    return TranscriptListFetcher(http_client).fetch(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 47, in fetch\n",
            "    self._extract_captions_json(self._fetch_video_html(video_id), video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 59, in _extract_captions_json\n",
            "    raise TranscriptsDisabled(video_id)\n",
            "youtube_transcript_api._errors.TranscriptsDisabled: \n",
            "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=undefined! This is most likely caused by:\n",
            "\n",
            "Subtitles are disabled for this video\n",
            "\n",
            "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
            "127.0.0.1 - - [14/Dec/2021 17:32:56] \"\u001b[35m\u001b[1mGET /summarize/?id=undefined&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 500 -\n",
            "[2021-12-14 17:32:57,796] ERROR in app: Exception on /summarize/ [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 2447, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1821, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 39, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"<ipython-input-17-7614ea4eb6dc>\", line 21, in transcript_fetched_query\n",
            "    transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 128, in get_transcript\n",
            "    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 70, in list_transcripts\n",
            "    return TranscriptListFetcher(http_client).fetch(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 47, in fetch\n",
            "    self._extract_captions_json(self._fetch_video_html(video_id), video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 59, in _extract_captions_json\n",
            "    raise TranscriptsDisabled(video_id)\n",
            "youtube_transcript_api._errors.TranscriptsDisabled: \n",
            "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=undefined! This is most likely caused by:\n",
            "\n",
            "Subtitles are disabled for this video\n",
            "\n",
            "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
            "127.0.0.1 - - [14/Dec/2021 17:32:57] \"\u001b[35m\u001b[1mGET /summarize/?id=undefined&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 500 -\n",
            "[2021-12-14 17:32:58,352] ERROR in app: Exception on /summarize/ [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 2447, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1821, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 39, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"<ipython-input-17-7614ea4eb6dc>\", line 21, in transcript_fetched_query\n",
            "    transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 128, in get_transcript\n",
            "    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 70, in list_transcripts\n",
            "    return TranscriptListFetcher(http_client).fetch(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 47, in fetch\n",
            "    self._extract_captions_json(self._fetch_video_html(video_id), video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 59, in _extract_captions_json\n",
            "    raise TranscriptsDisabled(video_id)\n",
            "youtube_transcript_api._errors.TranscriptsDisabled: \n",
            "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=undefined! This is most likely caused by:\n",
            "\n",
            "Subtitles are disabled for this video\n",
            "\n",
            "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
            "127.0.0.1 - - [14/Dec/2021 17:32:58] \"\u001b[35m\u001b[1mGET /summarize/?id=undefined&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 500 -\n",
            "[2021-12-14 17:32:58,746] ERROR in app: Exception on /summarize/ [GET]\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 2447, in wsgi_app\n",
            "    response = self.full_dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1952, in full_dispatch_request\n",
            "    rv = self.handle_user_exception(e)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1821, in handle_user_exception\n",
            "    reraise(exc_type, exc_value, tb)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/_compat.py\", line 39, in reraise\n",
            "    raise value\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1950, in full_dispatch_request\n",
            "    rv = self.dispatch_request()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/flask/app.py\", line 1936, in dispatch_request\n",
            "    return self.view_functions[rule.endpoint](**req.view_args)\n",
            "  File \"<ipython-input-17-7614ea4eb6dc>\", line 21, in transcript_fetched_query\n",
            "    transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 128, in get_transcript\n",
            "    return cls.list_transcripts(video_id, proxies, cookies).find_transcript(languages).fetch()\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_api.py\", line 70, in list_transcripts\n",
            "    return TranscriptListFetcher(http_client).fetch(video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 47, in fetch\n",
            "    self._extract_captions_json(self._fetch_video_html(video_id), video_id)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/youtube_transcript_api/_transcripts.py\", line 59, in _extract_captions_json\n",
            "    raise TranscriptsDisabled(video_id)\n",
            "youtube_transcript_api._errors.TranscriptsDisabled: \n",
            "Could not retrieve a transcript for the video https://www.youtube.com/watch?v=undefined! This is most likely caused by:\n",
            "\n",
            "Subtitles are disabled for this video\n",
            "\n",
            "If you are sure that the described cause is not responsible for this error and that a transcript should be retrievable, please create an issue at https://github.com/jdepoix/youtube-transcript-api/issues. Please add which version of youtube_transcript_api you are using and provide the information needed to replicate the error. Also make sure that there are no open issues which already describe your problem!\n",
            "127.0.0.1 - - [14/Dec/2021 17:32:58] \"\u001b[35m\u001b[1mGET /summarize/?id=undefined&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 500 -\n",
            "127.0.0.1 - - [14/Dec/2021 17:33:16] \"\u001b[37mGET /summarize/?id=lrEkYscgbqE&percent=20&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 200 -\n",
            "127.0.0.1 - - [14/Dec/2021 17:33:22] \"\u001b[31m\u001b[1mGET /summarize/?id=lrEkYscgbqE&percent=1&choice=sumy-lsa-sum HTTP/1.1\u001b[0m\" 400 -\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Comments downloading\n",
            "[============================================================] 100.0%\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "127.0.0.1 - - [14/Dec/2021 17:37:45] \"\u001b[37mGET /analysis/?id=lrEkYscgbqE HTTP/1.1\u001b[0m\" 200 -\n"
          ]
        }
      ],
      "source": [
        "@app.route(\"/\")\n",
        "def home():\n",
        "    print(request.base_url)\n",
        "    return jsonify({'msg':'success'})\n",
        "\n",
        "@app.route('/summarize/', methods=['GET'])\n",
        "def transcript_fetched_query():\n",
        "    # Getting argument from the request\n",
        "    video_id = request.args.get('id')  # video_id of the YouTube Video\n",
        "    percent = request.args.get('percent')  # percentage of the summary\n",
        "    choice = request.args.get('choice')  # summarization choice\n",
        "\n",
        "    # Checking whether all parameters exist or not\n",
        "    if video_id and percent and choice:\n",
        "        # Every parameter exists here: checking validity of choice\n",
        "        choice_list = [\"sumy-lsa-sum\", \"sumy-luhn-sum\", \"sumy-text-rank-sum\", \"sumy-lex-rank-sum\", \"sumy-klsum-rank-sum\" ]\n",
        "        if choice in choice_list:\n",
        "            # Choice Correct: Proceeding with Transcript Fetch and its Summarization\n",
        "            # Using Formatter to store and format received subtitles properly.\n",
        "            formatter = TextFormatter()\n",
        "            transcript = YouTubeTranscriptApi.get_transcript(video_id)\n",
        "            formatted_text = formatter.format_transcript(transcript).replace(\"\\n\", \" \")\n",
        "\n",
        "            # Checking the length of sentences in formatted_text string, before summarizing it.\n",
        "            num_sent_text = len(nltk.sent_tokenize(formatted_text))\n",
        "\n",
        "            # Pre-check if the summary will have at least one line .\n",
        "            select_length = int(num_sent_text * (int(percent) / 100))\n",
        "\n",
        "            # Summary will have at least 1 line. Proceed to summarize.\n",
        "            if select_length > 0:\n",
        "\n",
        "                # Condition satisfied for summarization, summarizing the formatted_text based on choice.\n",
        "                if num_sent_text > 1:\n",
        "\n",
        "                    # Summarizing Formatted Text based upon the request's choice\n",
        "                    if choice == \"sumy-lsa-sum\":\n",
        "                        summary = sumy_lsa_summarize(formatted_text,\n",
        "                                                      percent)  # Sumy for extractive summary using LSA.\n",
        "                    elif choice == \"sumy-luhn-sum\":\n",
        "                        summary = sumy_luhn_summarize(formatted_text,\n",
        "                                                      percent)  # Sumy Library for TF-IDF Based Summary.\n",
        "                    elif choice == \"sumy-text-rank-sum\":\n",
        "                        summary = sumy_text_rank_summarize(formatted_text,\n",
        "                                                            percent)  # Sumy for Text Rank Based Summary.\n",
        "                    elif choice == \"sumy-lex-rank-sum\":\n",
        "                        summary = sumy_lex_rank_summarize(formatted_text,\n",
        "                                                            percent)  # Sumy for Lex Rank Based Summary.\n",
        "                    elif choice == \"sumy-klsum-rank-sum\":\n",
        "                        summary = sumy_klsum_rank_summarize(formatted_text,\n",
        "                                                            percent)  # Sumy for Klsum Rank Based Summary.\n",
        "                    else:\n",
        "                        summary = None\n",
        "\n",
        "                    # Checking the length of sentences in summary string.\n",
        "                    num_sent_summary = len(nltk.sent_tokenize(summary))\n",
        "\n",
        "                    # Returning Result\n",
        "                    response_list = {\n",
        "                        # 'fetched_transcript': formatted_text,\n",
        "                        'processed_summary': summary,\n",
        "                        'length_original': len(formatted_text),\n",
        "                        'length_summary': len(summary),\n",
        "                    }\n",
        "\n",
        "                    return jsonify(success=True,\n",
        "                                    message=\"Subtitles for this video was fetched and summarized successfully.\",\n",
        "                                    response=response_list), 200\n",
        "\n",
        "                else:\n",
        "                    return jsonify(success=False,\n",
        "                                    message=\"Subtitles are not formatted properly for this video. Unable to \"\n",
        "                                            \"summarize. There is a possibility that there is no punctuation in \"\n",
        "                                            \"subtitles of your video.\",\n",
        "                                    response=None), 400\n",
        "\n",
        "            else:\n",
        "                return jsonify(success=False,\n",
        "                                message=\"Number of lines in the subtitles of your video is not \"\n",
        "                                        \"enough to generate a summary. Number of sentences in your video: {}\"\n",
        "                                .format(num_sent_text),\n",
        "                                response=None), 400\n",
        "\n",
        "        else:\n",
        "            return jsonify(success=False,\n",
        "                            message=\"Invalid Choice: Please create your request with correct choice.\",\n",
        "                            response=None), 400\n",
        "    elif video_id is None or len(video_id) <= 0:\n",
        "        # video_id parameter doesn't exist in the request.\n",
        "        return jsonify(success=False,\n",
        "                        message=\"Video ID is not present in the request. \"\n",
        "                                \"Please check that you have added id in your request correctly.\",\n",
        "                        response=None), 400\n",
        "    elif percent is None or len(percent) <= 0:\n",
        "        # percent parameter doesn't exist.\n",
        "        return jsonify(success=False,\n",
        "                        message=\"No Percentage value is present in the request. \"\n",
        "                                \"Please check whether your request is correct.\",\n",
        "                        response=None), 400\n",
        "    elif choice is None or len(choice) <= 0:\n",
        "        # choice parameter for the summary type doesn't exist here.\n",
        "        return jsonify(success=False,\n",
        "                        message=\"No Choice parameter is present in the request. \"\n",
        "                                \"Please request along with your choice correctly.\",\n",
        "                        response=None), 400\n",
        "    else:\n",
        "        # Some another edge case happened. Return this message for preventing exception throw.\n",
        "        return jsonify(success=False,\n",
        "                        message=\"Please request the server with your arguments correctly.\",\n",
        "                        response=None), 400\n",
        "\n",
        "@app.route('/analysis/', methods=['GET'])\n",
        "def videoAnalysis():\n",
        "  video_id = request.args.get('id') \n",
        "  comments = commentExtract(video_id)\n",
        "  result = sentiment(comments)\n",
        "  return jsonify(success=True,\n",
        "                message=\"Video Analysis completed\",\n",
        "                response=result), 200\n",
        "\n",
        "app.run()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "boIw0m3IP1vW"
      },
      "outputs": [],
      "source": [
        ""
      ]
    }
  ],
  "metadata": {
    "colab": {
      "collapsed_sections": [],
      "name": "MinorProject-NLPModelFlaskApp.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}